### ISSUE TITLE
Criar uma lista com todas as cartas do jogo

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#10]
Uma pessoa me deu a ideia de criar um lugar onde a pessoa possa visualizar todas as cartas do baralho, assim ela poderia avaliar os dados de um candidato específico, independente de ela ter a carta dentro do jogo ou não.

**Comment by netojoaobatista** [comment]
Acho que podemos ter uma página externa ao jogo, onde a pessoa pode ver, além das cartas do baralho, outros dados abertos. Isso melhorará a transparência e pode ser interessante para as pessoas conhecerem melhor os políticos.

Que acha @bernarddeluna, é viável uma página com todas as cartas e outros dados abertos?
