### ISSUE TITLE
Problema com "virada" da carta no Chrome

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#15]
No Chrome, quando seleciono um item do meu baralho, a carta do "oponente" deve virar, para mostrar os itens dele. Acontece que essa "virada" não está acontecendo no Chrome.
No Firefox, tudo acontece certinho, mas no Chrome a carta dá uma volta completa, voltando a ficar de cabeça para baixo.

Gravei um vídeo para mostrar o problema: https://www.youtube.com/watch?v=UMPeAHBl7Os

**Comment by fdaciuk** [comment]
Opa.. o problema só acontece no Chrome do Ubuntu: Ao virar a carta, o ".card-front" fica por trás do ".card-back". Colocando um z-index: 1 no card-front e um z-index: 0 no card-back na hora de virar acho que já resolve. Desculpe, nâo tive tempo de baixar o código ainda pra arrumar isso, mas como estava no Ubuntu, resolvi dar uma olhada. 

Assim que der um tempinho eu baixo aqui e tento arrumar isso ;)

**Comment by zenorocha** [comment]
Exatamente, o vídeo foi gravado em um sistema operacional Linux e só conseguimos visualizar esse problema nele. Windows e Mac funcionam bem de boa. Se puder dar uma olhada nisso seria extremamente legal @fdaciuk, estamos ultra atarefados na issue #3.

**Comment by zenorocha** [comment]
Pode me confirmar qual é o Pull Request certo @fdaciuk? #28 ou #29?

**Comment by fdaciuk** [comment]
Opa.. o correto é o #29. :)

**Comment by zenorocha** [comment]
Maravilha, estou fechando o #28 agora então, valeu! =D

**Comment by fdaciuk** [comment]
Melhor.. fecha as duas #28 e #29 que eu mando a alteração do tempo e da virada da carta no mesmo PR, pode ser?

**Comment by zenorocha** [comment]
Melhor não misturar, vai que rejeita uma ou outra saca?
Assim que fecharmos essa primeira te dou um toque.

**Comment by zenorocha** [comment]
Ah mas tudo bem, vi que você já enviou haahhaha

**Comment by fdaciuk** [comment]
Ops :x haha

**Comment by fdaciuk** [comment]
Mas se vc achar melhor @zenorocha, depois que aceitar a #29 eu mando essa outra de novo.. vc q manda ;)

**Comment by fdaciuk** [comment]
Acho que dá pra fechar essa issue :P
