### ISSUE TITLE
Atrasar a virada da carta do oponente

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#18]
Muitas pessoas estão reclamando que está muito rápido e não conseguem visualizar as informações da carta do oponente.

**Comment by fdaciuk** [comment]
Deixei a virada com 6s. Só não consegui fazer o PR, pois já tem um na fila, hehe!

Quando puder @zenorocha, pega o PR que fiz da issue #15 para eu poder enviar esse outro, ok? =)

**Comment by zenorocha** [comment]
Então, estou aguardando o @netojoaobatista avaliar aquele Pull Request.
Só ele pode aceitar tendo em vista que só ele está num Linux pra testar.

Vou fazer o seguinte, adicionei ele no [ROADMAP](https://github.com/transparencia/super-trunfo/blob/dev/ROADMAP.md) como a próxima tarefa.
Tenho a impressão que só segunda-feira será aceito porque @netojoaobatista estará no Intercon durante todo final de semana.

OBS: Acho 6 segundos muito, adicionaria só mais 1 segundo ao tempo atual pra não prejudicar a dinâmica da jogabilidade.

**Comment by fdaciuk** [comment]
Tranquilo.. vou deixar com 4s então. :)

**Comment by netojoaobatista** [comment]
Estamos pensando em uma outra pegada para essa situação.

Se o usuário colocar seu mouse sobre a outra carta, vamos pausar o timer. Assim, enquanto ele estiver com o mouse sobre a outra carta, ele poderá ver todos os atributos, ver outras informações, sem se preocupar com o timer.
