### ISSUE TITLE
Deixar explícito da onde são tirados os dados

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#19]

**Comment by netojoaobatista** [comment]
Em que lugar?

No source, no wiki, em uma documentação?

**Comment by zenorocha** [comment]
No source (botão de info) e na documentação. Deixa comigo.

Também deixar explícito em qual data foi obtido o dado. Isso porque pode ser que um político X tenha se livrado do processo hoje, e então entrar com um processo contra nós porque estamos divulgando dados não-reais.

**Comment by netojoaobatista** [comment]
Um ponto importante aqui, é que os processos que correm em primeira instância não são levados em consideração. Ou seja, o cara já teve o processo, já recorreu e já perdeu em segunda instância.

De qualquer forma, deixar explícito a data da última obtenção dos dados é importante pois estamos lidando com projetos, ou seja, frequentemente são aprovados, vetados e propostos novos projetos.

**Comment by zenorocha** [comment]
Maravilha. Então o que precisamos fazer é deixar explícito o que siginificam cada um dos atributos na interface do game.
