### ISSUE TITLE
Definir uma licença pro projeto

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#22]
E que não afete as outras licenças que estamos utilizando dos sites que obtemos os dados.

**Comment by zenorocha** [comment]
BSD? GPL? CC?

http://creativecommons.org.br/as-licencas/
http://pt.wikipedia.org/wiki/Licen%C3%A7as_BSD_e_GPL

**Comment by netojoaobatista** [comment]
E se usarmos a GPL CC?

http://www.softwarelivre.gov.br/Licencas/LicencaCcGplBr/
