### ISSUE TITLE
Nomes extrapolando espaço definido para eles

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#27]
Podemos até contar os caracteres e colocar 3 pontinhos se extrapolar, mas lembro de uma ideia que o @netojoaobatista teve para contar e cortar, se for necessário, o último nome.

**Comment by evertonfraga** [comment]
Fala Zeno, beleza? meus 2 cents pro ticket: https://github.com/evertonfraga/TextFit
um mini plugin que reduz o tamanho da fonte caso ela extrapole uma largura pré-definida. 
prefira usar a tag 0.1, que está em produção no techtudo.com.br e música.com.br. 
Abs!

**Comment by zenorocha** [comment]
Opa! Valeu a dica @evertonfraga, vou testar aqui.

**Comment by evertonfraga** [comment]
por nada @zenorocha , se precisar de alguma coisa é só falar

**Comment by zenorocha** [comment]
Muito obrigado @evertonfraga rolou direitinho! =D

**Comment by evertonfraga** [comment]
tamo junto, sucesso! =D
