### ISSUE TITLE
Localização do baralho via Facebook

### ISSUE THREAD

**Issue by netojoaobatista** [transparencia/super-trunfo#3]
O baralho, nesse instante, é um arquivo estático com os políticos de São Paulo. Precisamos localizar o baralho utilizando a informação de localização do usuário contida em seu perfil do Facebook.

**Comment by netojoaobatista** [comment]
Uma decisão precisa ser tomada aqui. Quando o usuário não tiver a informação de localização em seu perfil do Facebook, como faremos?
1. Deixaremos que ele escolha uma localização ao entrar no jogo.
2. Escolheremos um baralho padrão.

No caso da opção 1, permitiremos que qualquer pessoa escolha uma localização para jogar? Se sim, nesse caso, a própria escolha da localização seria um `enhancement`.

Que acham @zenorocha e @bernarddeluna?

**Comment by zenorocha** [comment]
Acho que poderíamos exibir no início uma opção para o jogador escolher qual cidade será o baralho dele.

Se conseguirmos obter a localização dele através do Facebook, deixamos a opção da cidade dele previamente escolhida.

**Comment by zenorocha** [comment]
@bernarddeluna se estiver de acordo, já pode ir tocando o visual disso.

**Comment by zenorocha** [comment]
Rio de Janeiro foi populado manualmente e já está online.

**Comment by zenorocha** [comment]
Analisei os dados do [Excelências - Transparência Brasil](http://www.excelencias.org.br/@casa.php?cs=30&casa=30) e montei [essa planilha](http://bit.ly/XbRsVo) que expõe as cidades que possuem informações sobre _Matérias legislativas_.

No fim, apenas 8 cidades possuem informações sobre isso: 
- Câmera Municipal de São Paulo
- Câmera Municipal de Fortaleza
- Câmera Municipal de Belo Horizonte
- Câmera Municipal de João Pessoa
- Câmera Municipal de Recife
- Câmera Municipal de Rio de Janeiro
- Câmera Municipal de Porto Alegre
- Câmera Municipal de Florianópolis

**Comment by zenorocha** [comment]
Agora precisamos rodar um crawler para buscar os dados dessas páginas, já que o XML não está disponível para todos os candidatos.

**Comment by zenorocha** [comment]
Além disso, é preciso adicionar a carta Super Trunfo dessas cidades.

**Comment by bernarddeluna** [comment]
acho que podemos nos focar em 3 cidades por dia... assim conseguimos testar
com bastante cuidado e força cada um dos releases

On Tue, Oct 23, 2012 at 11:18 PM, Zeno Rocha notifications@github.comwrote:

> Além disso, é preciso adicionar a carta Super Trunfo dessas cidades.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transparencia/super-trunfo/issues/3#issuecomment-9724550.

## 

Bernard De Luna F. F. Bittencourt
www.bernarddeluna.com
Twitter: @bernarddeluna
