### ISSUE TITLE
Mudar jogabilidade da carta Super Trunfo

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#33]
Hoje a jogabilidade da carta Super Trunfo se dá na seguinte forma.
Se a carta do oponente tiver A você perde, se não você vence automaticamente.

Segundo o @netojoaobatista, deveria ser da seguinte forma.
Se a carta do oponente tiver A, você disputa o atributo. Se não você vence automaticamente.

Poderia confirmar se é realmente assim @bernarddeluna?

**Comment by bernarddeluna** [comment]
não..

se é A, voce perde automaticamente, a jogabilidade atual está correta nesse
caso

2012/10/24 Zeno Rocha notifications@github.com

> Hoje a jogabilidade da carta Super Trunfo se dá na seguinte forma.
> Se a carta do oponente tiver A você perde, se não você vence
> automaticamente.
> 
> Segundo o @netojoaobatista https://github.com/netojoaobatista, deveria
> ser da seguinte forma.
> Se a carta do oponente tiver A, você disputa o atributo. Se não você vence
> automaticamente.
> 
> Poderia confirmar se é realmente assim @bernarddelunahttps://github.com/bernarddeluna
> ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transparencia/super-trunfo/issues/33.

## 

Bernard De Luna F. F. Bittencourt
www.bernarddeluna.com
Twitter: @bernarddeluna

**Comment by zenorocha** [comment]
João, pode nos confirmar a fonte dessa informação?
Assim avaliamos se isso entra no roadmap ou não...

**Comment by mkxml** [comment]
Pelo que sei é como o @bernarddeluna falou, se é A você já perdeu.
