### ISSUE TITLE
Compartilhar resultado

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#4]
Ao fim de cada partida, podemos  exibir ao usuário a opção de "Jogar Novamente" ou "Compartilhar seu resultado", em busca de viralizar ainda mais o jogo.

@bernarddeluna: Manda bala no visual disso.
@netojoaobatista: Manda bala na função de compartilhamento de status no Facebook.

**Comment by bernarddeluna** [comment]
Devemos gravar qnt tempo demorou a partida. Pois todos ganham e não temos como dizer pontuação, visto que todos ganham por 36x0.

Ou seja, podemos divulgar quanto tempo ganhou a partida, assim é uma boa métrica para se desafiar e montar um ranking.

**Comment by zenorocha** [comment]
Exatamente, podemos em um primeiro momento criar esse timer, porém sem armazenar em um ranking.
E assim que tivermos o módulo de multiplayer armazenar no banco de dados as estatísticas de cada jogador.

**Comment by zenorocha** [comment]
Aliás, no fim de cada partida temos que adicionar ainda mais uma opção que é "Voltar ao menu principal", permitindo assim que o usuário escolha outra cidade para brincar.

**Comment by zenorocha** [comment]
Estou fechando essa issue porque quebrei ela em duas e criei um milestone pra essa feature.

@netojoaobatista: #38
@bernarddeluna: #39

O prazo de publicação está definido pra terça-feira.
