### ISSUE TITLE
Erro ao acessar o app no facebook  

### ISSUE THREAD

**Issue by ribeiroevandro** [transparencia/super-trunfo#49]
Tentei o acesso hoje no jogo pelo facebook e foi exibido o erro abaixo:

Esta página da web tem um loop de redirecionamento
A página da web em https://neto.my.phpcloud.com/super-trunfo/ resultou em muitos redirecionamentos. Apagar seus cookies para este site ou permitir cookies de terceiros pode resolver o problema. Se não resolver, talvez o problema esteja na configuração do servidor, e não em seu computador.

**Comment by zenorocha** [comment]
@netojoaobatista poderia verificar?

**Comment by netojoaobatista** [comment]
Aparentemente, o problema é no phpcloud, que está caído.

> An Unexpected Error Has Occurred
> 
> It looks like some error has occurred, and the page you requested cannot be rendered. We suggest you try again at a later time.
> 
> In any case, our developers have been notified and will analyze and fix the problem ASAP.

**Comment by zenorocha** [comment]
https://github.com/transparencia/super-trunfo/issues/51
