### ISSUE TITLE
Rodar a app localmente

### ISSUE THREAD

**Issue by ribeiroevandro** [transparencia/super-trunfo#50]
Seria interessante um tutorial de usar rodar a aplicação localmente, isso irá facilitar para quem quiser fazer contribuições no projeto.

**Comment by zenorocha** [comment]
Tenta lá e me diz se conseguiu pra fechar ou não essa issue.

https://github.com/transparencia/super-trunfo#como-rodar-o-projeto-localmente

**Comment by ribeiroevandro** [comment]
Obrigado pela resposta rápida, porém não foi necessária a alteração do arquivo. De alguma forma, está funcionando...

**Comment by netojoaobatista** [comment]
A app já funciona em localhost sem precisar de nenhuma modificação.

Basta acessar localhost/super-trunfo que tudo funcionará.
