### ISSUE TITLE
Organizar estrutura das pastas

### ISSUE THREAD

**Issue by zenorocha** [transparencia/super-trunfo#7]
Precisamos organizar a atual árvore de diretórios para facilitar o entendimento de futuros contribuidores.

**Comment by netojoaobatista** [comment]
Hoje temos dois diretórios importantes:
- `public` - Esse cara é nosso DocumentRoot. Tudo o que estiver dentro dele é acessível via web.
- `src` - Esse cara é onde está o crawler. Ele não é acessível via web e é usado apenas internamente.

Outros diretórios que temos são:
- `mockups`
- `pages`
- `release`
- `visual`

O diretório `pages` foi movido para dentro de `public` e será removido da raiz. Os outros diretórios eu não sei, mas acho que, mas acho que `mockups` e `visual` podem ser removidos. O que são esses diretórios @bernarddeluna?

@zenorocha, o que é o diretório `release`? Ele será acessível via web? Ou é apenas um histórico de versões?
